spring.application.name=erp-mcp-server

# Datasource PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/erp
spring.datasource.username=erp
spring.datasource.password=erp


# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false


spring.ai.mcp.server.name=erp-mcp-server
spring.ai.mcp.server.version=0.0.1
spring.ai.mcp.server.protocol=STREAMABLE
